[tool.ruff]
line-length = 120
target-version = "py39"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "S",   # flake8-bandit (security)
]
ignore = [
    "S101",  # Use of assert - needed for tests
    "S603",  # Subprocess calls - needed for Chrome interaction
    "S607",  # Start process with partial path - osascript is a system command
    "S110",  # Try-except-pass - sometimes appropriate for optional operations
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S"]  # Ignore all security warnings in tests
