name: Python Tests

# Updated workflow to fix hanging tests in CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Create dummy env for testing
      run: |
        python ci_test_fix.py
    
    - name: Run tests with network isolation
      env:
        # These environment variables will make real network requests fail
        # This ensures our mocks are working properly
        PYTHONHTTPSVERIFY: "1" 
        REQUESTS_CA_BUNDLE: "/nonexistent"
        # Mock API key to avoid real API attempts
        FIREFLIES_API_KEY: "dummy-test-key-for-ci"
      run: |
        # Use pytest instead of unittest for better isolation
        python -m pytest tests/